[workspace]
members = ["packages/*", "contracts/*"]

[workspace.package]
version = "1.3.0"
edition = "2021"
license = "GPL 3.0"
repository = "https://github.com/cosmorama/wynd-lsd"

[workspace.dependencies]
anyhow = "1"
cosmwasm-schema = "3.0.4"
cosmwasm-std = { version = "3.0.4", features = ["staking"] }
cw2 = { path = "../cw-minus/packages/cw2" }
#cw20 = "2.0.0"
cw20            = { path = "../cw-plus/packages/cw20" }
#cw20-base = { version = "2.0.0", package = "cw20-base", features = ["library"] }
cw20-base       = { path = "../cw-plus/contracts/cw20-base" }
cw-controllers = { path = "../cw-minus/packages/controllers" }
cw-multi-test = { version = "3", features = ["staking"] }
#cw-placeholder = { version = "3.0", git = "https://github.com/cosmorama/wynddex.git", tag = "v2.0.2", features = ["library"] }
cw-placeholder = { path = "../wynddex/contracts/cw-placeholder",features = ["library"] }

cw-storage-plus = "3.0.1"
cw-utils = { path = "../cw-minus/packages/cw-utils" }
semver = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = "1"
wynd-lsd-hub = { path = "./contracts/lsd-hub", version = "1.3.0", features = ["library"] }
# wyndex = { version = "2.0", git = "https://github.com/cosmorama/wynddex.git", tag = "v2.0.2" }
wyndex = { path = "../wyndex" }
#wyndex-pair-lsd = { version = "2.0", git = "https://github.com/cosmorama/wynddex.git", tag = "v2.0.2", features = ["library"] }
wyndex-pair-lsd = {  path = "../wyndex", features = ["library"] }
test-case = "3.0.0"

[profile.release.package.wynd-lsd-hub]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
strip = true
