[workspace]
members = ["packages/*", "contracts/*"]

[workspace.package]
version = "1.3.0"
edition = "2021"
license = "GPL 3.0"
repository = "https://github.com/cosmorama/wynd-lsd"

[workspace.dependencies]
anyhow = "1"
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw2 = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
#cw20 = "2.0.0"
cw20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
#cw20-base = { version = "2.0.0", package = "cw20-base", features = ["library"] }
cw20-base = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw-controllers = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test", branch = "mvp" }
#cw-placeholder = { version = "3.0", git = "https://github.com/cosmorama/wynddex.git", tag = "v2.0.2", features = ["library"] }
cw-placeholder = { path = "../wynddex/contracts/cw-placeholder",features = ["library"] }

cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
semver = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = "1"
wynd-lsd-hub = { path = "./contracts/lsd-hub", version = "1.3.0", features = ["library"] }
# wyndex = { version = "2.0", git = "https://github.com/cosmorama/wynddex.git", tag = "v2.0.2" }
wyndex = { git = "https://github.com/permissionlessweb/wynddex", branch = "mvp" }
#wyndex-pair-lsd = { version = "2.0", git = "https://github.com/cosmorama/wynddex.git", tag = "v2.0.2", features = ["library"] }
wyndex-pair-lsd = {  path = "../wyndex", features = ["library"] }
test-case = "3.0.0"

[profile.release.package.wynd-lsd-hub]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
strip = true
